//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Emp_ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> EMP_DOB { get; set; }
        public string EmailId { get; set; }
        public int RoleID { get; set; }
    
        public virtual FK_Rolle_EMP FK_Rolle_EMP { get; set; }
    }
}
