//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_Rolle_EMP
    {
        public int ID { get; set; }
        public string FK_Rolle_EMP { get; set; }
    }
}
